"use client";
import { useState } from "react";
import { AlertTriangle, Globe, Plus, Trash2 } from "lucide-react";
import { useTranslation } from "@/i18n/useTranslation";
import { autoTranslate } from "../lib/translate";
import { classNames } from "../utils/class-names";
import { FOCUS_RING } from "./styles";
import { Button } from "./button"; import { Input } from "./input"; import { MarkdownEditor } from "./markdown-editor"; import { Select } from "./select"; import { Textarea } from "./textarea";
export interface Translation { languageCode: string; title: string; description: string; content?: string; }
interface LanguageOption { code: string; name: string; }
interface TranslationsFormProps { translations: Translation[]; onChange: (translations: Translation[]) => void; availableLanguages?: LanguageOption[]; showContent?: boolean; }
const DEFAULT_LANGUAGES: LanguageOption[] = [{ code: "es", name: "Español" }, { code: "en-us", name: "English" }, { code: "zh-Hans", name: "中文 (简体)" }];
const textLinkClasses = classNames("rounded", FOCUS_RING);
export function TranslationsForm({ translations, onChange, availableLanguages = DEFAULT_LANGUAGES, showContent = false }: TranslationsFormProps) {
  const t = useTranslation(); const [error, setError] = useState<string | null>(null);
  const addTranslation = () => { const language = availableLanguages.find(({ code }) => !translations.some((item) => item.languageCode === code)); if (!language) { setError(t("common.allLanguagesAdded")); return; } onChange([...translations, { languageCode: language.code, title: "", description: "", content: "" }]); setError(null); };
  const updateTranslation = (index: number, field: keyof Translation, value: string) => onChange(translations.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const translateFromSpanish = async (index: number) => { const translation = translations[index]; const spanish = translations.find(({ languageCode }) => languageCode === "es"); if (!spanish) return; try { const [title, description, content] = await Promise.all([autoTranslate(spanish.title, translation.languageCode), autoTranslate(spanish.description, translation.languageCode), showContent && spanish.content ? autoTranslate(spanish.content, translation.languageCode) : Promise.resolve("")]); onChange(translations.map((item, itemIndex) => itemIndex === index ? { ...item, title, description, content: showContent ? content : item.content } : item)); } catch { setError(t("common.errorTranslating")); } };
  return <div className="space-y-6"><div className="flex items-center justify-between border-b border-[rgb(var(--border))] pb-4"><div className="flex items-center gap-2 text-[rgb(var(--primary))]"><Globe size={18} /><h3 className="text-sm font-semibold">{t("common.translations")}</h3></div><Button onClick={addTranslation} disabled={translations.length >= availableLanguages.length} className="flex items-center gap-2"><Plus size={14} />{t("common.addLanguage")}</Button></div>{error && <div className="flex items-center gap-2 rounded-lg border border-[rgb(var(--cb-warning))] bg-[rgb(var(--cb-warning)/0.1)] p-3 text-sm text-[rgb(var(--warning-text))]"><AlertTriangle size={16} />{error}</div>}<div className="space-y-6">{translations.map((translation, index) => <div key={index} className="space-y-4 rounded-2xl border border-[rgb(var(--border))] bg-[rgb(var(--card))] p-5"><div className="flex items-center justify-between"><Select value={translation.languageCode} onChange={(event) => updateTranslation(index, "languageCode", event.target.value)}>{availableLanguages.map((language) => <option key={language.code} value={language.code} disabled={translations.some((item, itemIndex) => itemIndex !== index && item.languageCode === language.code)}>{language.name}</option>)}</Select>{translations.length > 1 && <button type="button" onClick={() => onChange(translations.filter((_, itemIndex) => itemIndex !== index))} className={classNames("flex items-center gap-1 text-sm text-[rgb(var(--error-text))] transition hover:opacity-80", textLinkClasses)}><Trash2 size={14} />{t("common.delete")}</button>}</div><div><label className="mb-1 block text-xs text-[rgb(var(--secondary-text))]">{t("common.title")}</label><Input value={translation.title} onChange={(event) => updateTranslation(index, "title", event.target.value)} placeholder={t("common.titlePlaceholder")} required /></div>{translation.languageCode !== "es" && <button type="button" onClick={() => void translateFromSpanish(index)} className={classNames("text-xs text-[rgb(var(--primary))] transition hover:opacity-80", textLinkClasses)}>{t("common.translateFromSpanish")}</button>}<div><label className="mb-1 block text-xs text-[rgb(var(--secondary-text))]">{t("common.description")}</label><Textarea value={translation.description} onChange={(event) => updateTranslation(index, "description", event.target.value)} rows={2} placeholder={t("common.descriptionPlaceholder")} /></div>{showContent && <div><label className="mb-1 block text-xs text-[rgb(var(--secondary-text))]">{t("common.contentMarkdown")}</label><MarkdownEditor value={translation.content ?? ""} onChange={(value) => updateTranslation(index, "content", value)} rows={8} /></div>}</div>)}</div></div>;
}
export default TranslationsForm;
