version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: codebuddies_postgres
    restart: always
    environment:
      POSTGRES_USER: codebuddies
      POSTGRES_PASSWORD: codebuddies
      POSTGRES_DB: codebuddies_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
